### ISSUE TITLE
Website link to InLab Explorer 404s if navigated from a page such as https://inlab.au/blog/

### ISSUE THREAD

**Issue by danekasper** [inlab-geo/inlab-geo.github.io#1]
Website link to InLab Explorer 404s if navigated from a page such as https://inlab.au/blog/

![image](https://github.com/inlab-geo/inlab-geo.github.io/assets/5305693/a9568af2-f19f-4c16-bdee-0e2b5eba8101)

**Comment by jwhhh** [comment]
Thanks for raising this issue! The link is fixed now.
